# Generated by Django 5.1.3 on 2024-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_invite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
